Import('qtEnv')
env = qtEnv.Clone()

env.EnableQt5Modules(['QtWidgets'])
env.Uic5(Glob('*.ui'))

env.Append(CPPPATH = ['#src/lib','#gen/lib'])
    
objects = env.Object(Glob('*.cpp')+Glob('*.qrc'))

Return('objects')

