Import('qtEnv')
env = qtEnv.Clone()

env.EnableQt5Modules(['QtWidgets'])

env.Append(CPPPATH = ['#src/lib','#gen/lib'])

env.Library('sim', SConscript('sim/SConscript'))
env.Library('springs', SConscript('springs/SConscript'))

