Import('qtEnv')
env = qtEnv.Clone()

if 'qt4' in qtEnv['TOOLS']:
    env.EnableQt4Modules(['QtGui'])
if 'qt5' in qtEnv['TOOLS']:
    env.EnableQt5Modules(['QtWidgets'])

env.Append(CPPPATH = '..')
    
objects = env.Object(Glob('*.cpp')+Glob('*.qrc'))

Return('objects')

